# Generated by Django 4.1.5 on 2023-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus_voltage_V', models.FloatField()),
                ('shunt_voltage_mV', models.FloatField()),
                ('load_voltage_V', models.FloatField()),
                ('current_mA', models.FloatField()),
                ('power_mW', models.FloatField()),
            ],
        ),
    ]
