# Generated by Django 4.1.5 on 2023-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryVoltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery_voltage', models.FloatField()),
            ],
        ),
    ]
